apiVersion: v1
kind: Secret
metadata:
  name: admin-secrets
  namespace: healthvault
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/healthvault
  NEXTAUTH_SECRET: super-secret-value
