apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nitishk21
type: Opaque
stringData:
  DATABASE_URL: postgresql://pgadmin:Password!@pg-learning.postgres.database.azure.com:5432/app_db?sslmode=require
