apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-config
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/healthvault"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "dummy-secret"
