# apiVersion: v1
# kind: Service
# metadata:
#   name: admin
# spec:
#   type: NodePort
#   selector:
#     app: admin
#   ports:
#     - port: 3000
#       targetPort: 3000
#       nodePort: 30007

apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: nitishk21
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
    - name: http
      port: 80
      targetPort: 3000


# apiVersion: v1
# kind: Service
# metadata:
#   name: admin
#   namespace: nitishk21
# spec:
#   type: NodePort
#   selector:
#     app: admin
#   ports:
#     - name: http
#       port: 80
#       targetPort: 3000
#       nodePort: 30080   # must be 30000â€“32767
