apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: healthvault
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prisma-migrate
          image: healthvault-admin:1.0
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: admin-secrets
