apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: nitishk21
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prisma-migrate
          image: nitishk21/my-app:latest
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: admin-secrets
